### ISSUE TITLE
[Semanário] Problemas vs. soluções em gerenciamento de produtos

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#3]
* [Problems, not solutions](https://ben.balter.com/2018/07/16/problems-not-solutions/). Ben Balter. 2018.

> The other way to think about talking in terms of problems instead of solutions is that you should spend more time talking about the “why”, than you spend talking about the “what”, or at least translating between the two.

**Comment by Andrelamor** [comment]
Temos alguns riscos implicitamente aceitos nas especificações que estão descritos neste post: realizar grande esforço para implementar uma alteração que pode não ser percebida como muito útil pelo usuário. Inclusive mapeamos esse risco no GT apropriado para tal, mas desconhecemos, de fato, a necessidade declarada de alguns 'personagens' usuários.

A conclusão remete também a um comportamento que ainda hoje não é raro na nossa burocracia: _As technologists, the solutions are the fun part. Many of us got into the field because we love building things or overcoming complex technical challenges._ Citação relacionada:
Os primeiros estudos de usuários remontam à década de 50, desenvolvidos
sob uma abordagem direcionada pela ótica do sistema de informação (MARTUCCI,
1997, p. 1; FERREIRA, 1995, p. 3), que considera a informação como algo
externo, objetivo, que existe fora do indivíduo e pode ser definida, medida e
utilizada por diferentes usuários da mesma forma, bastando ser descoberta.
Ancorada no processo de comunicação tradicional, a informação (mensagem) é
produzida por uma fonte e transmitida através de um canal com o objetivo de
reduzir a ambiguidade. O usuário é visto como um dos integrantes do sistema,
não a ‘razão de ser’ do serviço, posicionado passivamente e tendo de se adaptar
aos sistemas de informação, planejados em função das tecnologias utilizadas para
a sua implementação ou do conteúdo da informação a ser inserida nesses
sistemas, ao invés de serem moldados às características dos usuários a quem
deverá atender. Apesar dessa abordagem ter contribuído muito para a ciência da
informação, não conseguiu responder questões relativas ao ‘como’ as pessoas
fazem uso dos sistemas, ‘para qual finalidade’ e ‘como’ a informação obtida é
utilizada pelo usuário. Segundo Ferreira (1995, p. 4), dois aspectos relativos a
essa abordagem são questionáveis: 1) a irrelevância dada às incongruências
entre o que está contido no problema do usuário e o que está contido na pergunta
formulada; e 2) a falta de mecanismos nos sistemas de informação que consigam
identificar como o usuário pretende usar a informação obtida e como ele define a
sua relevância. (Vide http://www.scielo.br/pdf/pci/v15n3/10.pdf)

**Comment by silvianafaria** [comment]
:+1:
