### ISSUE TITLE
[Semanário] Organização de projetos de ciência de dados

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#7]
- [Cookiecutter Data Science](https://drivendata.github.io/cookiecutter-data-science/)

**Comment by Andrelamor** [comment]
É útil ter uma referência de estrutura ou hierarquia de pastas e arquivos de um projeto. Vamos padronizando os nossos, e, ao passo que eles ficam mais 'reprodutíveis', também podemos ganhar familiaridade nas pesquisas necessárias nos projetos de terceiros. Sobre isso, comentei em dois parágrafos específicos, que reproduzo abaixo:

> _A well-defined, standard project structure means that a newcomer can begin to understand an analysis without digging in to extensive documentation. It also means that they don't necessarily have to read 100% of the code before knowing where to look for very specific things._

Geralmente me sinto perdido quando preciso procurar alguma referência ou dica no repositório de outrem, não consigo reconhecer em qual pasta ou arquivo estaria o que poderia me auxiliar. Mas creio que essa percepção pode ter um fator adicional que é estar desfamiliarizado com as nomenclaturas das pastas e arquivos. 

> _Consistency within a project is more important. Consistency within one module or function is the most important. ... However, know when to be inconsistent -- sometimes style guide recommendations just aren't applicable. When in doubt, use your best judgment. Look at other examples and decide what looks best. And don't hesitate to ask!_

Julgamento é importante, mas parece ser difícil conseguir aplicá-lo bem quando ainda não se conhece razoavelmente bem todas as convenções e padrões necessários para a consistência e reprodutibilidade do projeto. Na fonte original dessa citação ([Style Guide for Python Code PEP 8](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)), pontua-se mais especificamente em quais situações os guidelines poderiam ser ignorados (mas entendo que para conseguir aplicar tais dicas, também é preciso um pouco de experiência para saber reconhecer as situações abaixo):

> _When applying the guideline would make the code less readable, even for someone who is used to reading code that follows this PEP.
To be consistent with surrounding code that also breaks it (maybe for historic reasons) -- although this is also an opportunity to clean up someone else's mess (in true XP style).
Because the code in question predates the introduction of the guideline and there is no other reason to be modifying that code.
When the code needs to remain compatible with older versions of Python that don't support the feature recommended by the style guide._ 

De qualquer forma, os autores deixam a opção de perguntar, sempre que houver uma dúvida sobre usar ou não uma convenção. Essa prática estaria em issues e foi [uma das dicas do semanário de comunicação assíncrona](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/#3-nobody-gets-fired-for-buying-ibm-opening-an-issue)

**Comment by silvianafaria** [comment]
:thumbsup:

**Comment by fjuniorr** [comment]
Na [minha aula da FJP](https://www.youtube.com/watch?v=0xNtq0adKbA) eu resumi a organização de projetos como sendo decisões sobre:

- Quais pastas devem ser criadas, com qual nome, e onde;
- Quais arquivos devem ser criados, com qual nome, e em que pasta;
- Em qual arquivo determinado conteúdo deve ser armazenado.

Como tomar decisão é cansativo, além dos benefícios de gestão do conhecimento, a inicialização de novos projetos ganha muita agilidade.
